# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/asautaux/yarr_fw/ip-cores/l2p_fifo64/l2p_fifo64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==l2p_fifo64 || ORIG_REF_NAME==l2p_fifo64}]

# IP: /home/asautaux/yarr_fw/ip-cores/fifo_64x512/fifo_64x512.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_64x512 || ORIG_REF_NAME==fifo_64x512}]

# IP: /home/asautaux/yarr_fw/ip-cores/fifo_96x512_1/fifo_96x512.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_96x512 || ORIG_REF_NAME==fifo_96x512}]

# IP: /home/asautaux/yarr_fw/ip-cores/fifo_32x512/fifo_32x512.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_32x512 || ORIG_REF_NAME==fifo_32x512}]

# IP: /home/asautaux/yarr_fw/ip-cores/fifo_4x16/fifo_4x16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_4x16 || ORIG_REF_NAME==fifo_4x16}]

# IP: /home/asautaux/yarr_fw/ip-cores/fifo_27x16/fifo_27x16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_27x16 || ORIG_REF_NAME==fifo_27x16}]

# IP: /home/asautaux/yarr_fw/ip-cores/fifo_256x16/fifo_256x16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_256x16 || ORIG_REF_NAME==fifo_256x16}]

# IP: /home/asautaux/yarr_fw/ip-cores/fifo_315x16/fifo_315x16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_315x16 || ORIG_REF_NAME==fifo_315x16}]

# IP: /home/asautaux/yarr_fw/ip-cores/mig_7series_0/mig_7series_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mig_7series_0 || ORIG_REF_NAME==mig_7series_0}]

# IP: /home/asautaux/yarr_fw/ip-cores/ila_l2p_dma/ila_l2p_dma.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_l2p_dma || ORIG_REF_NAME==ila_l2p_dma}]

# IP: /home/asautaux/yarr_fw/ip-cores/ila_ddr/ila_ddr.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_ddr || ORIG_REF_NAME==ila_ddr}]

# IP: /home/asautaux/yarr_fw/ip-cores/ila_wsh_pipe/ila_wsh_pipe.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_wsh_pipe || ORIG_REF_NAME==ila_wsh_pipe}]

# IP: /home/asautaux/yarr_fw/ip-cores/ila_axis/ila_axis.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_axis || ORIG_REF_NAME==ila_axis}]

# IP: /home/asautaux/yarr_fw/ip-cores/ila_pd_pdm/ila_pd_pdm.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_pd_pdm || ORIG_REF_NAME==ila_pd_pdm}]

# IP: /home/asautaux/yarr_fw/ip-cores/ila_dma_ctrl_reg/ila_dma_ctrl_reg.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_dma_ctrl_reg || ORIG_REF_NAME==ila_dma_ctrl_reg}]

# IP: /home/asautaux/yarr_fw/ip-cores/pcie_7x_0/pcie_7x_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_7x_0 || ORIG_REF_NAME==pcie_7x_0}]

# XDC: /home/asautaux/yarr_fw/syn/xpressk7/bram_revA/xpressk7.xdc
