---
stages:
  - build
  - package
  - tag
  - test
  - deploy

# If the pipeline is triggered by:
#    A merge request, run a merge request pipeline. For example, a merge request pipeline can be triggered by a push to a branch with an associated open merge request.
#    A change to a branch, but a merge request is open for that branch, do not run a branch pipeline.
#    A change to a branch, but without any open merge requests, run a branch pipeline.

.rules:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'
.tag:
  stage: tag
  image: gitlab-registry.cern.ch/ci-tools/docker-builder/tools
  variables:
    GIT_STRATEGY: none
  dependencies: []

# common build definitions
image: gitlab-registry.cern.ch/yarr/yarr_container:yarr_alma9_build
.build:
  stage: build
  extends: .rules

.build_matrix:
  extends: .build
  image: gitlab-registry.cern.ch/yarr/yarr_container:yarr_${ARCH}_build
  parallel:
    matrix:
      - ARCH: ['cc7', 'alma9']
.test:
  stage: test
  extends: .rules

.deploy:
  stage: deploy

###############
# Build Stage #
###############

job_build_all:
  extends: .build_matrix
  artifacts:
    paths:
      - bin
      - lib
      - python
  before_script:
    - git config --global user.email "ci@example.com"
    - git config --global user.name "CI Runner"
  script:
    - source scl_source enable devtoolset-9 || echo ignoring exit code so CI does not bomb when it should not > /dev/null
    - |
      if [ "$ARCH" = "cc7" ]; then
        yum -y install autoconf automake libtool glibc-headers kernel-headers
      else
        dnf -y install autoconf automake libtool
      fi
    - mkdir  build
    - cd build
    - cmake3 .. -DBUILD_TESTS=on -DCMAKE_TOOLCHAIN_FILE=../cmake/linux-gcc -DYARR_CONTROLLERS_TO_BUILD=all -DYARR_FRONT_ENDS_TO_BUILD=all -DYARR_ACTIVE_LOGGER_LEVEL=TRACE -DENABLE_PYTHON=On
    - make install -j$(nproc)
    - CTEST_OUTPUT_ON_FAILURE=1 make test
    - cd ..
    - bin/scanConsole -k

job_build_and_test_out_of_source:
  extends: .build_matrix
  stage: build
  script:
    - source scl_source enable devtoolset-9 || echo ignoring exit code so CI does not bomb when it should not > /dev/null
    - |
      if [ "$ARCH" = "cc7" ]; then
        yum -y install autoconf automake libtool glibc-headers kernel-headers
      else
        dnf -y install autoconf automake libtool
      fi
    - cmake3 --version
    - export YARR_PROJECT_DIR=`pwd`
    - CXXFLAGS=-Werror cmake3 -S . -B /tmp/build-yarr -DBUILD_TESTS=on -DCMAKE_TOOLCHAIN_FILE=cmake/linux-gcc -DCMAKE_INSTALL_PREFIX=/tmp/install-yarr
    - cmake3 --build /tmp/build-yarr -j$(nproc)
    - cmake3 --install /tmp/build-yarr
    - export Yarr_DIR=/tmp/install-yarr/cmake
    - ctest --output-on-failure --test-dir /tmp/build-yarr/
    - /tmp/install-yarr/bin/scanConsole -k
    - mkdir /tmp/build-YarrFindPackageTest
    - cmake3 -S tests/find_package_test -B /tmp/build-YarrFindPackageTest -DCMAKE_TOOLCHAIN_FILE=../../cmake/linux-gcc  -DCMAKE_INSTALL_PREFIX=/tmp/install-YarrFindPackageTest
    - cmake3 --build /tmp/build-YarrFindPackageTest -j$(nproc)
    - cmake3 --install /tmp/build-YarrFindPackageTest/
    - /tmp/install-YarrFindPackageTest/bin/YarrFindPackageTest
    - mkdir /tmp/build-YarrAddSubdirectoryTest
    - cmake3 -S tests/add_subdirectory_test -B /tmp/build-YarrAddSubdirectoryTest -DCMAKE_TOOLCHAIN_FILE=../../cmake/linux-gcc  -DCMAKE_INSTALL_PREFIX=/tmp/install-YarrAddSubdirectoryTest
    - cmake3 --build /tmp/build-YarrAddSubdirectoryTest -j$(nproc)
    - cmake3 --install /tmp/build-YarrAddSubdirectoryTest/
    - /tmp/install-YarrAddSubdirectoryTest/bin/YarrAddSubdirectoryTest
    - mkdir /tmp/build-YarrExternalSuperbuildTest
    - cmake3 -S tests/external_project_superbuild_test -B /tmp/build-YarrExternalSuperbuildTest -DCMAKE_TOOLCHAIN_FILE=../../cmake/linux-gcc  -DCMAKE_INSTALL_PREFIX=/tmp/install-YarrExternalSuperbuildTest -DYARR_PROJECT_DIR=$YARR_PROJECT_DIR
    - cmake3 --build /tmp/build-YarrExternalSuperbuildTest -j$(nproc)
    - cmake3 --install /tmp/build-YarrExternalSuperbuildTest/
    - /tmp/install-YarrExternalSuperbuildTest/bin/YarrConsumerTest
    - mkdir /tmp/build-YarrFetchContentTest
    - cmake3 -S tests/fetch_content_test -B /tmp/build-YarrFetchContentTest -DCMAKE_TOOLCHAIN_FILE=../../cmake/linux-gcc  -DCMAKE_INSTALL_PREFIX=/tmp/install-YarrFetchContentTest -DYARR_PROJECT_DIR=$YARR_PROJECT_DIR
    - cmake3 --build /tmp/build-YarrFetchContentTest -j$(nproc)
    - cmake3 --install /tmp/build-YarrFetchContentTest/
    - /tmp/install-YarrFetchContentTest/bin/YarrFetchContentTest

job_build_clang:
  extends: .build_matrix
  stage: build
  script:
    - source scl_source enable devtoolset-9 || echo ignoring exit code so CI does not bomb when it should not > /dev/null
    - source scl_source enable llvm-toolset-11.0 || echo ignoring exit code so CI does not bomb when it should not > /dev/null
    - mkdir -p build
    - cd build
    - CXXFLAGS=-Werror cmake3 .. -DBUILD_TESTS=on -DCMAKE_TOOLCHAIN_FILE=../cmake/linux-clang
    - make install -j$(nproc)
    - CTEST_OUTPUT_ON_FAILURE=1 make test
    - cd ..
    - bin/scanConsole -k

job_build_none:
  extends: .build_matrix
  script:
    - source scl_source enable devtoolset-9 || echo ignoring exit code so CI does not bomb when it should not > /dev/null
    - mkdir build
    - cd build
    - cmake3 .. -DBUILD_TESTS=on -DCMAKE_TOOLCHAIN_FILE=../cmake/linux-gcc -DYARR_CONTROLLERS_TO_BUILD= -DYARR_FRONT_ENDS_TO_BUILD= -DYARR_ACTIVE_LOGGER_LEVEL=OFF
    - make install -j$(nproc)
    - CTEST_OUTPUT_ON_FAILURE=1 make test
    - cd ..
    - bin/scanConsole -k

.build_felix:
  stage: build
  image: gitlab-registry.cern.ch/atlas-tdaq-felix/gitlab_ci_runner:el9-netboot-dev
  tags:
    - k8s-cvmfs
  artifacts:
    paths:
      - installed
  script:
    - git clone https://gitlab.cern.ch/atlas-tdaq-felix/cmake_tdaq
    - source cmake_tdaq/bin/setup.sh
    - mkdir installed
    - cmake -S . -B build -DYARR_CONTROLLERS_TO_BUILD="Spec;Emu;StarEmu;Rd53aEmu;FelixClient" -DYARR_FRONT_ENDS_TO_BUILD="Rd53a;Star;Rd53b;Itkpixv2" -DDISABLE_PLOTTING_TOOLS=On -DYARR_EMULATORS_TO_BUILD="StarEmu;Rd53aEmu"  -DENABLE_PYTHON=On  ..
    - cmake --build build -j$(nproc)
    - cmake --install build
    - cp -r Dockerfile bin lib python installed/

job_build_felix:
  extends: .build_felix
  only:
    - devel
    - tags

job_build_felix_check:
  extends: [.build_felix, .rules]


.job_code_coverage:
  stage: build
  artifacts:
    paths:
      - cc_tests
  script:
    - date
    - source scl_source enable devtoolset-9 || echo ignoring exit code so CI does not bomb when it should not > /dev/null
    - mkdir  build
    - cd build
    - cmake3 .. -DBUILD_TESTS=on -DCMAKE_BUILD_TYPE=Coverage -DCMAKE_TOOLCHAIN_FILE=../cmake/linux-gcc
    - make install -j$(nproc)
    - /bin/pwd
    - cd ../
    - source scl_source enable devtoolset-9 || echo ignoring exit code so CI does not bomb when it should not > /dev/null
    - scripts/cc_tool.sh
  coverage: '/  lines......: \d+(?:\.\d+)?/'

job_code_coverage:
  extends: [".job_code_coverage", ".rules"]

job_code_coverage_deploy:
  extends: .job_code_coverage
  only:
    - devel
    - master

job_run_codechecker:
  stage: build
  timeout: 3 hours
  only:
    - merge_requests
  script:
    - source scl_source enable devtoolset-9 || echo ignoring exit code so CI does not bomb when it should not > /dev/null
    - source scl_source enable llvm-toolset-11.0 || echo ignoring exit code so CI does not bomb when it should not > /dev/null
    - scripts/run_codechecker.sh -j$(nproc)
  after_script:
    - cat gl-code-quality-report.json
  artifacts:
    paths:
      - checks
      - gl-code-quality-report.json
    reports:
      codequality: gl-code-quality-report.json

job_yamllint:
  extends: .build
  before_script:
    - pip install yamllint
  script:
    - yamllint .

.job_build_doxygen:
  stage: build
  before_script:
    - yum install -y doxygen graphviz
  script:
    - doxygen Doxyfile
  artifacts:
    paths:
      - doxygen/html

job_build_doxygen:
  extends: [".job_build_doxygen", ".rules"]

job_build_doxygen_deploy:
  extends: .job_build_doxygen
  only:
    - devel
    - master

.build_docs:
  stage: build
  before_script:
    - pip install mkdocs
  script:
    - export LC_ALL=en_US.utf-8
    - export LANG=en_US.utf-8
    - mkdocs build
  artifacts:
    paths:
      - site

build_docs:
  extends: [".build_docs", ".rules"]

build_docs_deploy:
  extends: .build_docs
  only:
    - devel
    - master

#################
# Package Stage #
#################

build_container:
  stage: package
  only:
    - devel
    - tags
  trigger:
    include:
      - project: 'ci-tools/docker-builder'
        file: '/ci.yml'
    strategy: depend
  variables:
    BUILD_AARCH64: "false"
    TO: "${CI_REGISTRY_IMAGE}"
    CONTEXT_DIR: installed
    DOCKER_FILE: installed//Dockerfile
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
    ARTIFACT_JOB: job_build_felix

###############
# Test Stage #
###############

job_test_pixel:
  extends: .test
  needs:
    - job: job_build_all
      parallel:
        matrix:
          - ARCH: ['alma9']
  script:
    - bin/scanConsole -r configs/controller/emuCfg.json -c configs/connectivity/example_fei4b_setup.json -s configs/scans/fei4/std_digitalscan.json -p -l configs/logging/trace_all.json
    - ls
    - ls ./data/
    - ls ./data/000001_std_digitalscan/
    - cat ./data/000001_std_digitalscan/*_OccupancyMap.json
    - NUM100=`cat ./data/000001_std_digitalscan/*_OccupancyMap.json | grep -o 100 | wc -l`
    - if ["$NUM100" != "26880"]; then exit 2; fi
    - bin/scanConsole  -r configs/controller/emuCfg_rd53a.json -c configs/connectivity/example_rd53a_setup.json -s configs/scans/rd53a/std_digitalscan.json
    - ls
    - ls ./data/
    - ls ./data/000002_std_digitalscan/
    - cat ./data/000002_std_digitalscan/*_OccupancyMap.json
    - NUM100=`cat ./data/000002_std_digitalscan/*_OccupancyMap.json | grep -o 100 | wc -l`
    - if ["$NUM100" != "76800"]; then exit 2; fi

job_test_strips:
  extends: .test
  needs:
    - job: job_build_all
      parallel:
        matrix:
          - ARCH: ['alma9']
  script:
    - bin/test_star configs/controller/emuCfg_star.json -r 0 -t 0
    # Run a scan involving trim feedback
    - bin/scanConsole -r configs/controller/emuCfg_star.json -c configs/connectivity/example_star_setup.json -s configs/scans/star/std_tune_trim_at_pedestal.json

job_test_benchmark:
  extends: .test
  needs:
    - job: job_build_all
      parallel:
        matrix:
          - ARCH: ['alma9']
  script:
    - bin/testUtil '[!benchmark]' > testUtils.benchmark
    - bin/testYarr '[!benchmark]' > testYarr.benchmark
    - . scripts/run_strips_benchmarks.sh > star_processor_benchmarks.benchmark
  artifacts:
    paths:
      - '*.benchmark'

job_test_python:
  extends: .test
  needs:
    - job: job_build_all
      parallel:
        matrix:
          - ARCH: ['alma9']
  script:
    - PYTHONPATH=$PWD/lib python3 python/scan_cli_logger.py -r configs/controller/emuCfg_rd53a.json -c configs/connectivity/example_rd53a_setup.json -s configs/scans/rd53a/std_digitalscan.json

job_test_json_parsing:
  extends: .test
  needs:
    - job: job_build_all
      parallel:
        matrix:
          - ARCH: ['alma9']
  script:
    # Check schema by loading configs in turn
    - (for file in $(find configs/defaults -iname "*.json"); do echo ${file}; bin/test_json -f ${file} -t FRONT_END || exit; done)
    - (for file in $(find configs/connectivity -iname "*.json"); do echo ${file}; bin/test_json -f ${file} -t CONNECTIVITY || exit; done)
    - (for file in $(find configs/controller -iname "*.json"); do echo ${file}; bin/test_json -f ${file} -t CONTROLLER || exit; done)
    - (for file in $(find configs/scans/* -iname "*.json"); do echo ${file}; bin/test_json -f ${file} -t SCAN_CONFIG || exit; done)

job_test_netio:
  extends: .test
  needs:
    - job: job_build_all
      parallel:
        matrix:
          - ARCH: ['cc7']
  image: gitlab-registry.cern.ch/yarr/yarr_container:yarr_cc7_build
  script:
    # Launch netio_bridge to connect an emulator to NetIO
    - bin/netio_bridge -p 12340 -q 12350 -f configs/controller/emuCfg_star.json & pid_bridge=($!)
    - sleep 1
    # Run scans with the NetIO controller
    - bin/scanConsole -r configs/controller/felix_netio_strips.json -c configs/connectivity/example_star_setup.json -s configs/scans/star/std_regDump.json
    - bin/scanConsole -r configs/controller/felix_netio_strips.json -c configs/connectivity/example_star_setup.json -s configs/scans/star/std_latencyScan.json -p
    # Terminate netio_bridge
    - kill ${pid_bridge}

job_test_json:
  extends: .test
  script:
    - source scl_source enable rh-nodejs6 || echo ignoring exit code so CI does not bomb when it should not > /dev/null
    - npm install jsonlint -g
    - for file in $(find configs/ -iname "*.json"); do echo ${file}; jsonlint -q ${file} || break -1; done

################
# Deploy Stage #
################

deploy_master:
  extends: .deploy
  dependencies: ["build_docs_deploy"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PROJECT_PATH == "YARR/YARR"'
  variables:
    "EOS_PATH": "/eos/user/t/theim/www/yarr"
    "CI_OUTPUT_DIR": "site/"
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer
  script:
    - deploy-eos

deploy_devel:
  extends: .deploy
  dependencies: ["build_docs_deploy"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "devel" && $CI_PROJECT_PATH == "YARR/YARR"'
  variables:
    "EOS_PATH": "/eos/user/t/theim/www/yarr/devel"
    "CI_OUTPUT_DIR": "site/"
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer
  script:
    - deploy-eos

deploy_devel_doxygen:
  extends: .deploy
  dependencies: ["job_build_doxygen_deploy"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "devel" && $CI_PROJECT_PATH == "YARR/YARR"'
  variables:
    "EOS_PATH": "/eos/user/t/theim/www/yarr/doxygen/devel/"
    "CI_OUTPUT_DIR": "doxygen/html/"
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer
  script:
    - mkdir -p /eos/user/t/theim/www/yarr/doxygen/devel/
    - deploy-eos

deploy_coverage:
  extends: .deploy
  dependencies: ["job_code_coverage_deploy"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "devel" && $CI_PROJECT_PATH == "YARR/YARR"'
  variables:
    "EOS_PATH": "/eos/user/t/theim/www/yarr/devel/coverage"
    "CI_OUTPUT_DIR": "cc_tests/"
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer
  script:
    - deploy-eos

#############
# Tag Stage #
#############

tag_latest_devel_container:
  extends: .tag
  needs:
    - build_container
  script:
    - /kaniko/auth.sh
    - crane tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}" "devel"
    - crane validate --remote "${CI_REGISTRY_IMAGE}:devel"
  only:
    - devel

tag_latest_release_container:
  extends: .tag
  needs:
    - build_container
  script:
    - /kaniko/auth.sh
    - crane tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}" "${CI_COMMIT_TAG}"
    - crane validate --remote "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
    - crane tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}" "latest"
    - crane validate --remote "${CI_REGISTRY_IMAGE}:latest"
  only:
    - tags
