#ifndef HCC_STAR_CFG_INCLUDE
#define HCC_STAR_CFG_INCLUDE

#include "enum.h"

//Different HCC registers that can be used
BETTER_ENUM(HCCStarRegister, int,
            Pulse=16, Delay1=32, Delay2=33, Delay3=34,
            PLL1=35, PLL2=36, PLL3=37, DRV1=38, DRV2=39,
            ICenable=40, OPmode=41, OPmodeC=42, Cfg1=43, Cfg2=44,
            ExtRst=45, ExtRstC=46, ErrCfg=47, ADCcfg=48)
//Different HCC subregisters that can be used for configuration, scans, etc.
////NOTE: If the name is changed here, make sure the corresponding subregister name is also changed in the config json file.
BETTER_ENUM(HCCStarSubRegister, int,
            STOPHPR=1,
            CFD_BC_FINEDELAY, CFD_BC_COARSEDELAY, CFD_PRLP_FINEDELAY, CFD_PRLP_COARSEDELAY, HFD_LCBA_FINEDELAY, FD_RCLK_FINEDELAY, LCBA_DELAY160,
            FD_DATAIN0_FINEDELAY, FD_DATAIN1_FINEDELAY, FD_DATAIN2_FINEDELAY, FD_DATAIN3_FINEDELAY, FD_DATAIN4_FINEDELAY, FD_DATAIN5_FINEDELAY, FD_DATAIN6_FINEDELAY, FD_DATAIN7_FINEDELAY,
            FD_DATAIN8_FINEDELAY, FD_DATAIN9_FINEDELAY, FD_DATAIN10_FINEDELAY,
            EPLLICP, EPLLCAP, EPLLRES, EPLLREFFREQ, EPLLENABLEPHASE,
            EPLLPHASE320A, EPLLPHASE320B, EPLLPHASE320C, EPLLPHASE160A, EPLLPHASE160B, EPLLPHASE160C,
            STVCLKOUTCUR, STVCLKOUTEN, LCBOUTCUR, LCBOUTEN, R3L1OUTCUR, R3L1OUTEN, BCHYBCUR, BCHYBEN, LCBAHYBCUR, LCBAHYBEN, PRLPHYBCUR, PRLPHYBEN, RCLKHYBCUR, RCLKHYBEN,
            DATA1CUR, DATA1ENPRE, DATA1ENABLE, DATA1TERM, DATACLKCUR, DATACLKENPRE, DATACLKENABLE,
            ICENABLE, ICTRANSSEL,
            TRIGMODE, ROSPEED, OPMODE, MAXNPACKETS, ENCODECNTL, ENCODE8B10B, PRBSMODE,
            TRIGMODEC, ROSPEEDC, OPMODEC, MAXNPACKETSC, ENCODECNTLC, ENCODE8B10BC, PRBSMODEC,
            BGSETTING, MASKHPR, GPO0, GPO1, EFUSEPROGBIT,
            BCIDRSTDELAY, BCMMSQUELCH,
            ABCRESETB, AMACSSSH, ABCRESETBC, AMACSSSHC,
            LCBERRCOUNTTHR, R3L1ERRCOUNTTHR,
            AMENABLE, AMCALIB, AMSW0, AMSW1, AMSW2, AMSW60, AMSW80, AMSW100, ANASET, THERMOFFSET)

#endif
