YARR_ADD_PYBIND11()
pybind11_add_module(_pyyarr src/_pyyarr.cpp)
target_link_libraries(_pyyarr PRIVATE Yarr Scan)
install(DIRECTORY tools/ DESTINATION ${CMAKE_INSTALL_PREFIX}/python
        FILES_MATCHING PATTERN "*.py")
install(DIRECTORY pyYARR/ DESTINATION ${CMAKE_INSTALL_PREFIX}/python/pyYARR
        FILES_MATCHING PATTERN "*.py")
        
install(TARGETS _pyyarr
    EXPORT Yarr_PythonTargets
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}  # For DLLs on Windows
    INCLUDES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
  )
  
install(EXPORT Yarr_PythonTargets
  NAMESPACE Yarr::
  DESTINATION ${CMAKE_CONFIG_INSTALL_PATH}/Yarr
)
