files = ["clk_gen.vhd",
         "ila.ngc",
         "ila_icon.ngc",
         "fifo_64x512.ngc",
         "fifo_32x512.ngc",
         "l2p_fifo.ngc",
         "rx_bridge_fifo.ngc",
         "rx_channel_fifo.ngc",
         "rx_bridge_ctrl_fifo.ngc",
         "ila.vhd",
         "ila_icon.vhd",
         "fifo_64x512.vhd",
         "fifo_32x512.vhd",
         "l2p_fifo.vhd",
         "rx_bridge_fifo.vhd",
         "rx_channel_fifo.vhd",
         "rx_bridge_ctrl_fifo.vhd"]
